<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="3" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[UID & PWD Entered]]>
    </line>
    <line>
      <![CDATA[TC Passed]]>
    </line>
    <line>
      <![CDATA[UID & PWD Entered]]>
    </line>
    <line>
      <![CDATA[UID & PWD Entered]]>
    </line>
    <line>
      <![CDATA[UID & PWD Entered]]>
    </line>
    <line>
      <![CDATA[TC Passed]]>
    </line>
    <line>
      <![CDATA[UID & PWD Entered]]>
    </line>
  </reporter-output>
  <suite started-at="2022-11-13T16:09:29 IST" name="Suite" finished-at="2022-11-13T16:10:32 IST" duration-ms="63711">
    <groups>
    </groups>
    <test started-at="2022-11-13T16:09:29 IST" name="Test" finished-at="2022-11-13T16:10:32 IST" duration-ms="63711">
      <class name="com.SdetBanking.TestCases.TC_LoginTest_DDT_002">
        <test-method is-config="true" signature="setProperty(java.lang.String)[pri:0, instance:com.SdetBanking.TestCases.TC_LoginTest_DDT_002@2d710f1a]" started-at="2022-11-13T16:09:29 IST" name="setProperty" finished-at="2022-11-13T16:09:40 IST" duration-ms="11718" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setProperty -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:com.SdetBanking.TestCases.TC_LoginTest_DDT_002@2d710f1a]" started-at="2022-11-13T16:09:43 IST" name="loginTest" data-provider="LoginData" finished-at="2022-11-13T16:09:55 IST" duration-ms="11794" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr347425]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pAgemeb]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[UID & PWD Entered]]>
            </line>
            <line>
              <![CDATA[TC Passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:com.SdetBanking.TestCases.TC_LoginTest_DDT_002@2d710f1a]" started-at="2022-11-13T16:09:55 IST" name="loginTest" data-provider="LoginData" finished-at="2022-11-13T16:10:03 IST" duration-ms="7676" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr347426]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pAgemeb]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.SdetBanking.TestCases.TC_LoginTest_DDT_002.loginTest(TC_LoginTest_DDT_002.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[UID & PWD Entered]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:com.SdetBanking.TestCases.TC_LoginTest_DDT_002@2d710f1a]" started-at="2022-11-13T16:10:03 IST" name="loginTest" data-provider="LoginData" finished-at="2022-11-13T16:10:10 IST" duration-ms="7460" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr347427]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pAgemeb]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.SdetBanking.TestCases.TC_LoginTest_DDT_002.loginTest(TC_LoginTest_DDT_002.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[UID & PWD Entered]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:com.SdetBanking.TestCases.TC_LoginTest_DDT_002@2d710f1a]" started-at="2022-11-13T16:10:10 IST" name="loginTest" data-provider="LoginData" finished-at="2022-11-13T16:10:23 IST" duration-ms="13006" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr347425]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pAgemeb]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[UID & PWD Entered]]>
            </line>
            <line>
              <![CDATA[TC Passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:com.SdetBanking.TestCases.TC_LoginTest_DDT_002@2d710f1a]" started-at="2022-11-13T16:10:23 IST" name="loginTest" data-provider="LoginData" finished-at="2022-11-13T16:10:31 IST" duration-ms="7911" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr347429]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pAgemeb]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.SdetBanking.TestCases.TC_LoginTest_DDT_002.loginTest(TC_LoginTest_DDT_002.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[UID & PWD Entered]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.SdetBanking.TestCases.TC_LoginTest_DDT_002@2d710f1a]" started-at="2022-11-13T16:10:31 IST" name="tearDown" finished-at="2022-11-13T16:10:32 IST" duration-ms="1237" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.SdetBanking.TestCases.TC_LoginTest_DDT_002 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
